"""table - address added street

Revision ID: d23096a85b31
Revises: 0826f29cd729
Create Date: 2024-02-04 17:25:20.242154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23096a85b31'
down_revision: Union[str, None] = '0826f29cd729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('street', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'street')
    # ### end Alembic commands ###
